package net.derbyparty.jpp.object;

public enum RaceType {
	GRADE_1,	// G1
	GRADE_2,	// G2
	GRADE_3,	// G3
	NON_GRADED,	// N
	ALLOWANCE,	// A
	STARTER_ALLOWANCE,	// R
	STARTER_HANDICAP,	// T
	CLAIMING,	// C
	OPTIONAL_CLAIMING,	// CO
	MAIDEN_SPECIAL_WEIGHT,	// S
	MAIDEN_CLAIMING,	// M
	ALLOWANCE_OPTIONAL_CLAIMING,	// AO
	MAIDEN_OPTIONAL_CLAIMING,	// MO
	OPTIONAL_CLAIMING_STAKES	// NO
}
